server:
  port: 7780 # 端口

spring:
  application:
    name: config-client # 应用名称

# 自定义配置
name: config-client-prod
password: '{cipher}c8c81f02adf4406628a9c440c3fabfed575201ac09848c90aa9c2abb77f2d32e'
